exasol/exasol-testcontainers

- README.md
- launch/testcontainer install.launch
- pom.xml
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/test/java/com/exasol/bucketfs/BucketTest.java
> #8: Fixed transitive dependencies.

- doc/user_guide/user_guide.md
- src/main/java/com/exasol/bucketfs/Bucket.java
- src/test/java/com/exasol/bucketfs/BucketTest.java
> #11: Improved path handling in buckets.

- doc/system_requirements.md
- doc/user_guide/user_guide.md
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/main/java/com/exasol/containers/ExasolContainerConstants.java
- src/main/java/com/exasol/containers/ExasolContainerProvider.java
- src/test/java/com/exasol/clusterlogs/MappedClusterLogsTest.java
> 13: Collect logs from the container

- .travis.yml
- doc/design.md
- doc/system_requirements.md
- pom.xml
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/main/java/com/exasol/containers/ExasolContainerConstants.java
- src/main/java/com/exasol/containers/wait/LogFileEntryWaitStrategy.java
- src/test/java/com/exasol/clusterlogs/MappedClusterLogsTest.java
- src/test/java/com/exasol/config/ClusterConfigAccessTest.java
- src/test/java/com/exasol/containers/ExasolContainerTest.java
- src/test/java/com/exasol/containers/ExasolContainerWaitStrategyTest.java
> #12: Container now waits until UDF language container is ready.

- doc/user_guide/user_guide.md
- src/test/java/com/exasol/bucketfs/BucketTest.java
> #10: Improvements for BucketFS documentation

- doc/design.md
- doc/system_requirements.md
- doc/user_guide/user_guide.md
- pom.xml
- src/main/java/com/exasol/bucketfs/Bucket.java
- src/main/java/com/exasol/bucketfs/BucketFactory.java
- src/main/java/com/exasol/clusterlogs/LogPatternDetector.java
- src/main/java/com/exasol/clusterlogs/LogPatternDetectorFactory.java
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/main/java/com/exasol/containers/ExasolContainerConstants.java
- src/main/java/com/exasol/containers/wait/strategy/LogFileEntryWaitStrategy.java
- src/test/java/com/exasol/bucketfs/BucketContentSyncTest.java
- src/test/java/com/exasol/bucketfs/BucketFactoryTest.java
- src/test/java/com/exasol/bucketfs/BucketTest.java
- src/test/java/com/exasol/bucketfs/RandomFileGenerator.java
- src/test/java/com/exasol/containers/ExasolContainerTest.java
- src/test/java/com/exasol/containers/ExasolContainerWaitStrategyTest.java
Polls the BucketFS daemon log for messages that show that the object is synchronized.
Closes #19.
> #19: Waiting for BucketFS content sync.

- pom.xml
- src/main/java/com/exasol/containers/ExasolContainer.java
Closes #24.
Task-Url: http://github.com/exasol/exasol-testcontainers/issues/24
> 24: Read cluster configuration directly after it becomes available

- .travis.yml
- pom.xml
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/test/java/com/exasol/bucketfs/BucketContentSyncIT.java
- src/test/java/com/exasol/bucketfs/BucketIT.java
- src/test/java/com/exasol/clusterlogs/MappedClusterLogsIT.java
- src/test/java/com/exasol/config/ClusterConfigAccessIT.java
- src/test/java/com/exasol/containers/ExasolContainerDefaultsIT.java
- src/test/java/com/exasol/containers/ExasolContainerIT.java
- src/test/java/com/exasol/containers/ExasolContainerWaitStrategyIT.java
Closes #26.
Task-Url: http://github.com/exasol/exasol-testcontainers/issues/26
> #26: Separate unit tests from integration tests

- .classpath
- .settings/org.eclipse.core.resources.prefs
- doc/design.md
- doc/system_requirements.md
- doc/user_guide/user_guide.md
- pom.xml
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/test/java/com/exasol/containers/ExasolContainerDefaultsIT.java
- src/test/java/com/exasol/containers/ExasolContainerIT.java
- src/test/java/com/exasol/exaloader/ExaLoaderBetweenTwoContainersIT.java
> #29: ExaLoader in one container imports from another container

- doc/user_guide/user_guide.md
Closes #32.
Task-Url: http://github.com/exasol/exasol-testcontainers/issues/32
> #32: Documentation: How to use with mvn

- doc/user_guide/user_guide.md
fixed case sensitivity and arguments for Plugin example to match actual interface implementation
> fixed examples in user guide

- pom.xml
- src/main/java/com/exasol/exaoperation/plugin/Plugin.java
- src/test/java/com/exasol/exaoperation/plugin/PluginTest.java
> #44: Allow dash in plug-in package name.

- launch/testcontainer verify.launch
- pom.xml
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/main/java/com/exasol/containers/ExasolService.java
- src/test/java/com/exasol/containers/ExasolContainerTest.java
> #56: DatabaseService::start() does not wait until database is ready for connections

- doc/changes/changes-2.0.3.md
- src/main/java/com/exasol/exaoperation/ExaOperationEmulator.java
> #66: Fixed requirements tracing.

- .travis.yml
- doc/changes/changes-2.0.3.md
- doc/changes/changes-2.1.0.md
- doc/design.md
- doc/system_requirements.md
- doc/user_guide/user_guide.md
- pom.xml
- src/main/java/com/exasol/bucketfs/Bucket.java
- src/main/java/com/exasol/clusterlogs/LogPatternDetector.java
- src/main/java/com/exasol/clusterlogs/LogPatternDetectorFactory.java
- src/main/java/com/exasol/config/ClusterConfiguration.java
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/main/java/com/exasol/containers/ExasolContainerConstants.java
- src/main/java/com/exasol/containers/ExasolDockerImageReference.java
- src/main/java/com/exasol/containers/wait/strategy/BucketFsWaitStrategy.java
- src/main/java/com/exasol/containers/wait/strategy/LogFileEntryWaitStrategy.java
- src/main/java/com/exasol/containers/wait/strategy/UdfContainerWaitStrategy.java
- src/main/java/com/exasol/exaoperation/ExaOperationEmulator.java
- src/test/java/com/exasol/bucketfs/BucketContentSyncIT.java
- src/test/java/com/exasol/bucketfs/BucketIT.java
- src/test/java/com/exasol/containers/ExasolContainerTest.java
- src/test/java/com/exasol/containers/ExasolDockerImageReferenceTest.java
- src/test/java/com/exasol/containers/MessageWriter.java
- src/test/java/com/exasol/containers/OptionalServicesIT.java
- src/test/java/com/exasol/containers/wait/strategy/AbstractServiceWaitStrategyTest.java
- src/test/java/com/exasol/containers/wait/strategy/BucketFsWaitStrategyTest.java
- src/test/java/com/exasol/containers/wait/strategy/UdfContainerWaitStrategyTest.java
- src/test/java/com/exasol/exaconf/ConfigurationParserTest.java
- src/test/resources/logging.properties
> #54: Fix wait when replacing file in bucket

- doc/changes/changelog.md
- doc/changes/changes_3.2.0.md
- pom.xml
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/test/java/com/exasol/containers/ExasolContainerTest.java
> #92 Made connection timeout configurable

- doc/changes/changelog.md
- doc/changes/changes_3.3.0.md
- doc/design.md
- doc/system_requirements.md
- pom.xml
- src/main/java/com/exasol/bucketfs/Bucket.java
- src/test/java/com/exasol/bucketfs/BucketIT.java
> #77 Upload input stream to BucketFS

- doc/changes/changes_3.3.0.md
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/main/java/com/exasol/containers/wait/strategy/LogFileEntryWaitStrategy.java
> #97: Increased BucketFS timeout

- .travis.yml
- doc/changes/changelog.md
- doc/changes/changes_3.4.0.md
- doc/design.md
- doc/system_requirements.md
- doc/user_guide/user_guide.md
- pom.xml
- src/main/java/com/exasol/bucketfs/Bucket.java
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/main/java/com/exasol/containers/ExasolContainerConstants.java
- src/test/java/com/exasol/containers/DockerImageOverrideIT.java
> #106: Override docker image via property

- doc/changes/changelog.md
- doc/changes/changes_3.3.2.md
- src/main/java/com/exasol/clusterlogs/LogPatternDetector.java
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/test/java/com/exasol/containers/ExasolContainerProviderTest.java
- src/test/java/com/exasol/containers/ExasolContainerResuseIT.java
- src/test/java/com/exasol/containers/ExasolContainerTest.java
> #108: Fix Eclipse warnings in version 3.3.1

- .travis.yml
- doc/changes/changelog.md
- doc/changes/changes_3.5.0.md
- doc/design.md
- doc/system_requirements.md
- pom.xml
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/main/java/com/exasol/containers/ExasolContainerConstants.java
- src/main/java/com/exasol/containers/HostIpDetector.java
- src/test/java/com/exasol/containers/HostIpDetectorTest.java
- src/test/java/com/exasol/containers/HostIpDetectorTestIT.java
Closes #58.
Updated test container basis. Closes #122.
> #58: Implement getHostIp()

- doc/changes/changelog.md
- doc/changes/changes_3.5.3.md
- pom.xml
- release_config.yml
- src/main/java/com/exasol/exaconf/ConfigurationParser.java
- src/test/java/com/exasol/exaconf/ConfigurationParserTest.java
> #136: Fixed parsing of EXAConfig with root password set

- doc/changes/changes_4.0.0.md
- doc/design.md
- doc/system_requirements.md
- src/main/java/com/exasol/containers/DockerImageReferenceFactory.java
- src/main/java/com/exasol/containers/ExasolDockerImageReference.java
- src/main/java/com/exasol/containers/LiteralExasolDockerImageReference.java
- src/main/java/com/exasol/containers/VersionBasedExasolDockerImageReference.java
- src/test/java/com/exasol/containers/ExasolDockerImageReferenceTest.java
> #142: Recognize non-production docker version numbers

- doc/changes/changes_4.0.0.md
- src/main/java/com/exasol/bucketfs/testcontainers/TestcontainerBucketFactory.java
- src/main/java/com/exasol/drivers/DatabaseDriver.java
- src/main/java/com/exasol/drivers/JdbcDriver.java
- src/main/java/com/exasol/exaoperation/plugin/Plugin.java
- src/test/java/com/exasol/config/BucketFsServiceConfigurationTest.java
- src/test/java/com/exasol/exaoperation/ExaOperationEmulatorIT.java
- src/test/java/com/exasol/exaoperation/ExaOperationEmulatorTest.java
- src/test/java/com/exasol/exaoperation/plugin/PluginTest.java
> #146: Fix Sonar findings for release 4.0.0

- .github/workflows/ci-build.yml
- dependencies.md
- doc/changes/changes_4.0.0.md
- error_code_config.yml
- pom.xml
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/main/java/com/exasol/containers/HostIpDetector.java
- src/main/java/com/exasol/containers/LiteralExasolDockerImageReference.java
- src/main/java/com/exasol/drivers/JdbcDriver.java
> #148: Run CI on pull-request

- src/main/java/com/exasol/database/DatabaseService.java
- src/test/java/com/exasol/containers/wait/strategy/AbstractServiceWaitStrategyTest.java
> #150: Fix more SonarCloud issues in 4.0.0

- doc/changes/changelog.md
- doc/changes/changes_5.1.1.md
- pom.xml
- src/main/java/com/exasol/containers/tls/CertificateProvider.java
> Reduce log verbosity

- .github/workflows/broken_links_checker.yml
- .github/workflows/ci-build-next-java.yml
- doc/changes/changes_5.1.2.md
- pom.xml
- src/test/java/com/exasol/containers/wait/strategy/AbstractServiceWaitStrategyTest.java
- src/test/java/com/exasol/containers/wait/strategy/BucketFsWaitStrategyTest.java
- src/test/java/com/exasol/containers/wait/strategy/UdfContainerWaitStrategyTest.java
> #165: Sped up wait strategy tests

- doc/changes/changes_6.1.0.md
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/test/java/com/exasol/containers/ExasolContainerIT.java
- src/test/java/com/exasol/containers/tls/TlsConnectionIT.java
> #180: Moved fingerprint to JDBC URL parameter.

- doc/changes/changes_6.1.0.md
> Updated date for release 6.1.0.

- .github/workflows/ci-build.yml
- doc/changes/changelog.md
- doc/changes/changes_6.1.2.md
- pom.xml
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/main/java/com/exasol/containers/ExasolContainerConstants.java
> #193: Uniform JDBC URL

- release_config.yml
> release config

- .vscode/settings.json
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_6.4.0.md
- pk_generated_parent.pom
- pom.xml
> #209: Used JDBC driver from Maven Central

- .project-keeper.yml
- doc/changes/changelog.md
- doc/changes/changes_6.5.0.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/main/java/com/exasol/containers/ssh/DirectorySelector.java
- src/test/java/com/exasol/containers/ssh/DirectorySelectorTest.java
- src/test/java/com/exasol/containers/ssh/DockerAccessTest.java
> Implemented #215

- .project-keeper.yml
- dependencies.md
- doc/changes/changes_6.5.0.md
- pom.xml
- src/test/java/com/exasol/clusterlogs/LogPatternDetectorTest.java
- src/test/java/com/exasol/containers/ExasolContainerTest.java
- src/test/java/com/exasol/containers/workarounds/LogRotationWorkaroundTest.java
- src/test/java/com/exasol/exaoperation/plugin/PluginIT.java
- src/test/java/com/exasol/exaoperation/plugin/PluginTest.java
- src/test/java/com/exasol/testutil/VarArgsMatcher.java
> Updated dependencies

- .github/workflows/ci-build.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_6.6.0.md
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/containers/DockerImageReferenceFactory.java
- src/main/java/com/exasol/containers/ExasolContainerConstants.java
- src/main/java/com/exasol/containers/ExasolDockerImageReference.java
- src/main/java/com/exasol/containers/LiteralExasolDockerImageReference.java
- src/main/java/com/exasol/containers/VersionBasedExasolDockerImageReference.java
- src/test/java/com/exasol/containers/ExasolDockerImageReferenceTest.java
- src/test/java/com/exasol/containers/tls/TlsConnectionIT.java
> #200: Updated matrix build to use Exasol 8 and enable pre-release prefix

- .github/workflows/ci-build.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_6.6.1.md
- doc/system_requirements.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/containers/ExasolContainerConstants.java
- src/main/java/com/exasol/drivers/ExasolDriverManager.java
- src/main/java/com/exasol/drivers/JdbcDriver.java
- src/test/java/com/exasol/drivers/DerbyConnectionTestUdf.java
- src/test/java/com/exasol/drivers/ExasolDriverManagerIT.java
- src/test/java/com/exasol/drivers/JdbcDriverTest.java
> #228: Integration test for DriverManager

- .github/workflows/broken_links_checker.yml
- .github/workflows/ci-build-next-java.yml
- .github/workflows/ci-build.yml
- .github/workflows/dependencies_update.yml
- .project-keeper.yml
- .vscode/settings.json
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_7.1.1.md
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/bucketfs/testcontainers/TestcontainerBucketFactory.java
- src/main/java/com/exasol/config/ClusterConfiguration.java
- src/main/java/com/exasol/containers/ExasolContainer.java
- src/main/java/com/exasol/containers/ExasolContainerConstants.java
- src/test/java/com/exasol/bucketfs/testcontainers/BucketIT.java
- src/test/java/com/exasol/bucketfs/testcontainers/TestcontainerBucketFactoryTest.java
- src/test/java/com/exasol/drivers/LocalDerbyServer.java
- src/test/java/com/exasol/exaconf/ConfigurationParserTest.java
> #258: Adapt to Exasol 8.29.1

- SECURITY.md
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_7.1.4.md
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/containers/ExasolContainerIT.java
Closes #267
Contains https://github.com/exasol/exasol-testcontainers/pull/266
> #267: Fix NoSuchMethodError at container startup
